### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by hrdzkj** [yangjiechina/JGB28181#2]
请问这个报错，是那里配置不对呢
javax.sip.InvalidArgumentException: java.net.BindException: Address already in use (Bind failed)
	at gov.nist.javax.sip.SipStackImpl.createListeningPoint(SipStackImpl.java:1677)
	at com.yangjie.JGB28181.message.SipLayer.initSip(SipLayer.java:165)
	at com.yangjie.JGB28181.message.SipLayer.startServer(SipLayer.java:146)
	at com.yangjie.JGB28181.message.config.SipLayerConfig.sipLayer(SipLayerConfig.java:40)
	at com.yangjie.JGB28181.message.config.SipLayerConfig$$EnhancerBySpringCGLIB$$6d4f3bb6.CGLIB$sipLayer$0(<generated>)
	at com.yangjie.JGB28181.message.config.SipLayerConfig$$EnhancerBySpringCGLIB$$6d4f3bb6$$FastClassBySpringCGLIB$$3bc1b657.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358)
	at com.yangjie.JGB28181.message.config.SipLayerConfig$$EnhancerBySpringCGLIB$$6d4f3bb6.sipLayer(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

![报错](https://user-images.githubusercontent.com/12473177/77819926-8fdd7d80-7119-11ea-8a4d-e6fbac035b56.png)
![配置](https://user-images.githubusercontent.com/12473177/77819929-966bf500-7119-11ea-950d-f8012f2addd4.png)

**Comment by hrdzkj** [comment]
关闭了java.exe重启后正常了
